#!/usr/bin/env bash
# This file creates a redirection from the original site
sudo apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/www.jw.org permanent;/" /etc/nginx/sites-available/default
sudo service nginx restart
