#!/usr/bin/env bash
# This file creates a custom error page
sudo apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
sudo touch /usr/share/nginx/html/custom_404.html
sudo chmod u+w /usr/share/nginx/html/custom_404.html
# This script's main purpose is to create a custom 404 page
sudo apt-get -y update
sudo apt-get -y install nginx

echo 'Hello World!' > /var/www/html/index.html
sudo echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sudo sed -i '/listen 80 default_server;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}' /etc/nginx/sites-available/default
sudo service nginx restart
