#!/usr/bin/env bash
# This script changes the localhost on ubuntu

cp /etc/hosts ~/hosts.new
echo -e "127.0.0.2 \tlocalhost" > ~/hosts.new
echo -e "8.8.8.8 \tfacebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
